# Generated by Django 5.1.1 on 2024-09-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='dummy_field',
            field=models.CharField(default='x', editable=False, max_length=1),
        ),
    ]
