# Generated by Django 5.1.1 on 2024-09-22 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0003_delete_jobpost_remove_imagepost_dummy_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('experience', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_1.userprofile')),
            ],
        ),
    ]
